---
- hosts: all
  become: sudo
  tasks:
    - name: Replace ES_PORT
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: "\'{{ lookup ('ini', 'ES_PORT, type=properties file=elastic.properties')}}'"
        replace: "{{ lookup('ini', 'ES_PORT, type=properties file=elastic.properties') }}"
        backup: yes