---
# tasks file for /etc/ansible/GIT/Dimko/roles/Filebeat
- hosts: all
  become: sudo
  tasks:
    - name: Download filebeat
      shell: wget -q -O $1/$FILEBEAT_PACKAGE --ftp-user=acm --ftp-password=acm ftp://172.27.1.100/$FILEBEAT_PACKAGE
	  
    - name: Make directories
      file:
        path: /opt/filebeat/{{item}}
        state: directory
        mode: 0755
      with_items:
      - /private
      - /certs
      
    - name: Installing filebeat
      shell: |
        tar xvzf $1/$FILEBEAT_PACKAGE -C /opt/filebeat --strip-components=1 || fail "!> Failed to install FileBeat"
        sed -i "s|\$FILEBEAT_DIR|$FILEBEAT_DIR|g" "$1/$FILEBEAT_SCRIPT"
        sed -i "s|\$FILEBEAT_SERVICE_USER|$FILEBEAT_SERVICE_USER|g" "$1/$FILEBEAT_SCRIPT"
        
    - name: Creating FileBeat User
      shell: useradd $FILEBEAT_SERVICE_USER
      
    - name: Setting password for FileBeat user
      shell: |
      echo -e "$FILEBEAT_SERVICE_PASS\n$FILEBEAT_SERVICE_PASS" | passwd $FILEBEAT_SERVICE_USER
      unset FILEBEAT_SERVICE_PASS
      
    - name: Setting ownership for FileBeat user to filebeat directory
      shell: chown -R $FILEBEAT_SERVICE_USER:$FILEBEAT_SERVICE_USER $FILEBEAT_DIR
      
    - name: Copy filebeat script to init.directories
      shell: cp $1/$FILEBEAT_SCRIPT /etc/init.d/filebeat
      
    - name: Make filebeat executable
      shell: chmod +x /etc/init.d/filebeat
      
    - name: Copy the certificates to remote machine
      copy:
        src: /etc/ansible/filebeat/certs
        dest: /tmp/filebeat/certs
        
    - name: Install certificates for filebeat->logstash tls communication
      copy:
        src: /tmp/filebeat/certs/acm-elasticsearch-server-client.cert.pem
        dest: ????
        remote_src: yes
        
    - name: Install certificates for filebeat->logstash tls communication 2
      copy:
        src: /tmp/filebeat/certs/acm-elasticsearch-server-client.key.pem
        dest: ????
        remote_src: yes
        
    - name: Install certificates for filebeat->logstash tls communication 3
      copy:
        src: /tmp/filebeat/certs/ca-chain.cert.pem
        dest: ????
        remote_src: yes
        
    - name: Change ownership
      shell: chown -R filebeat.filebeat $FILEBEAT_DIR/
      
    - name: Adding filebeat to startup and shutdown scripts
      shell: |
        echo '/etc/init.d/filebeat start' >> /usr/local/bin/startup.sh
        echo '/etc/init.d/filebeat stop' >> /usr/local/bin/shutdown.sh