---
# tasks file for /etc/ansible/GIT/Dimko/roles/Logstash
    - name: Create the directories
      file:
        path: /opt/logstash/{{item}}
        state: directory
        mode: 0755
      with_items:
      - /logs
      - /certs
      - /private
      - /data

    - name: Copy the LogStash binary
      copy: 
        src: "{{ LOGSTASH_PACKAGE }}"
        dest: /tmp/logstash/
       
    - name: Install LogStash
      yum:
        name: /tmp/logstash/{{ LOGSTASH_PACKAGE }}
        state: present

    - name: Delete the binary
      file:
        path: /tmp/logstash/
        state: absent

## DA SE ISKOPIRAAT OD /role/file direktrno na lokacijata i 
## soodvetno na toa da se prasa David dali da se kopiraat vo opt ili etc
##    - name: Copy the certificates
##      copy:
##      src: /opt/ansible/GIT/Dimko/roles/Logstash/files/certs/
##      dest: /opt/certs/
        
    - name: Install the certificates
      copy:
        src: acm-elasticsearch-server-client.key.pkcs8
        dest: /opt/logstash/private/
        
    - name: Install the certifites 2
      copy:
        src: acm-elasticsearch-server-client.cert.pem
        dest: /opt/logstash/certs/
        
    - name: Install the certificates 3
      copy:
        src: ca-chain.cert.pem
        dest: /opt/logstash/certs/
        
    - name: Install the certificates 4
      copy:
        src: ca-chain.cert.pem
        dest: /etc/pki/ca-trust/source/anchors/

    - name: Create trustStore jks file, needed by logstash
      shell: |
        yes |  keytool -import -file /opt/logstash/certs/ca-chain.cert.pem -alias caChain -storepass AcMd3v -keystore /opt/logstash/certs/logstashTrustStore.jks
        update-ca-trust force-enable
        update-ca-trust extract
        
    - name: Change the ownership on all files in /opt/logstash/
      file: 
        dest: /opt/logstash/
        owner: logstash
        group: logstash
        mode: 0755
        recurse: yes
      
    - name: Copy Logstash Config files
      copy:
        src: /conf/"{{ item }}"
        dest: /etc/logstash/
        with_items:
          - 01-input.conf
          - 99-output.conf
          - alfresco.conf
          - elk.conf
          - frevvo.conf
          - pentaho.conf
          - mysql.conf
          - snowbound.conf
          - solr.conf
        
## Error when executing with path: /opt since file is in etc        
    - name: Replace LS_SETTINGS_DIR
      replace:
        path: /opt/logstash/startup.options
        regexp: LS_SETTINGS_DIR=/etc/logstash
        replace: LS_SETTINGS_DIR=/opt/logstash
        backup: yes

    - name: Replace path.config
      replace:
        path: /opt/logstash/logstash.yml
        regexp: 'path.config: /etc/logstash/conf.d'
        replace: 'path.config: /opt/logstash/conf.d'
        backup: yes
        
    - name: Add username and pass to logstash.yml
      shell: |
        echo xpack.monitoring.elasticsearch.username: logstash_system >> logstash.yml
        echo xpack.monitoring.elasticsearch.password: logstashpass >> logstash.yml
        /usr/share/logstash/bin/system-install /opt/logstash/startup.options sysv
        $LS_HOME/bin/system-install $LS_START_UP_OPTIONS_PATH/startup.options sysv
## Wait on Marjan

    - name: Replace KILL_ON_STOP_TIMEOUT
      replace:
        path: /etc/init.d/logstash
        regexp: 'KILL_ON_STOP_TIMEOUT=0'
        replace: 'KILL_ON_STOP_TIMEOUT=1'
        backup: yes
        
    - name: Change LOGSTASH_MYSQL_PORT
      replace:
        path: /etc/logstash/{{LOGSTASH_CONFIG_FILE_01}}
        regexp: '\\$LOGSTASH_MYSQL_PORT'
        replace: '{{ LOGSTASH_MYSQL_PORT }}'
        backup: yes

    - name: Change LOGSTASH_SNOWBOUND_PORT
      replace:
        path: /etc/logstash/{{LOGSTASH_CONFIG_FILE_01}}
        regexp: '\\$LOGSTASH_SNOWBOUND_PORT'
        replace: '{{ LOGSTASH_SNOWBOUND_PORT }}'
        backup: yes

    - name: Change LOGSTASH_PENTAHO_PORT
      replace:
        path: /etc/logstash/{{LOGSTASH_CONFIG_FILE_01}}
        regexp: '\\$LOGSTASH_PENTAHO_PORT'
        replace: '{{ LOGSTASH_PENTAHO_PORT }}'
        backup: yes

    - name: Change ELK_PORT
      replace:
        path: /etc/logstash/{{LOGSTASH_CONFIG_FILE_01}}
        regexp: '\\$ELK_PORT'
        replace: '{{ ELK_PORT }}'
        backup: yes

    - name: Change LOGSTASH_ALF_PORT
      replace:
        path: /etc/logstash/{{LOGSTASH_CONFIG_FILE_01}}
        regexp: '\\$LOGSTASH_ALF_PORT'
        replace: '{{ LOGSTASH_ALF_PORT }}'
        backup: yes

    - name: Change ES_PORT
      replace:
        path: /etc/logstash/{{LOGSTASH_CONFIG_FILE_99}}
        regexp: '\\$ES_PORT'
        replace: '{{ ES_PORT }}'
        backup: yes
##    - name: Copy logstash_configs
##      copy:
##        src: /etc/ansible/GIT/Dimko/roles/Logstash/files/logstash_configs
##        dest: /opt/logstash/

##    - name: Adding LogStash service to autostart
##      service: name=logstash enabled=yes
     
    - name: Adding LogStash to startup.sh & shutdown.sh scripts
      shell: |
        echo '/etc/init.d/logstash start' >> /usr/local/bin/startup.sh
        echo '/etc/init.d/logstash stop' >> /usr/local/bin/shutdown.sh
        
    - name: Copy logstash config files in the logstast conf.d folder
      copy:
        src: /etc/logstash/
        dest: /opt/logstash/conf.d/