---
# tasks file for /etc/ansible/GIT/Dimko/roles/installCarte
    - name: Transfer and unzip the carte installation files to the remote host
      unarchive:
        src:
        dest: /opt/app/acm/pentaho/
    
    - name: Change ownership of all files in data-integration folder
      file:
        path: /opt/app/acm/pentaho/data-integration/
        state: directory
        recurse: yes
        owner: pentaho
        group: pentaho
        mode: 755
        
    - name: Replace line in carte-config-master-8080.xml file
      replace:
        path: /opt/app/acm/pentaho/data-integration/pwd/carte-config-master-8080.xml
        regexp: '<hostname>localhost</hostname>'
        replace: '<hostname>0.0.0.0</hostname>'
      
    - name: Replace line in the kettle.pwd file
      replace:
        path: /opt/app/acm/pentaho/data-integration/pwd/kettle.pwd
        regexp: 'cluster: OBF:1v8w1uh21z7k1ym71z7i1ugo1v9q'
        replace: 'arkcase-carte: OBF:18da1okw1e3f1iz21j1s1e1v1oi618bk'
        
    - name: Add localhost as acm-carte in hosts file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1 acm-carte'
        
    - name: Add reverse proxy configuration
      blockinfile:
        path: '/opt/app/acm/httpd/conf/extra/httpd-ssl.conf'
        block: |
          ProxyPass /kettle http://acm-carte:8080/kettle
          ProxyPassReverse /kettle http://acm-carte:8080/kettle
          
          ProxyPass /static http://acm-carte:8080/static
          ProxyPassReverse /static http://acm-carte:8080/static
          
    - name: Restart the httpd service
      systemd:
        state: restarted
        name: apachectl
        
    - name: Copy the service file to systemd
      copy:
        src: carte.service
        dest: /usr/lib/systemd/system/carte.service
        owner: root
        group: root
        mode: 664
        
    - name: Execute enable service
      shell: "sudo systemctl enable /usr/lib/systemd/system/carte.service"
      
    - name: Execute daemon-reload
      systemd:
        daemon_reload: yes