---
# tasks file for UpdateSnowbound
    - name: Create the directory for snowbound.war deployment
      stat:
        path: /opt/app/acm/snowbound
        state: directory
      register: state

    - name: Copy the new snowbound war file
      copy:
        src: VirtualViewerJavaHTML5.war
        dest: /opt/app/acm/snowbound/webapps/VirtualViewerJavaHTML5.war
        backup: yes
      when: state.stat.isdir is defined and state.stat.isdir
        
    - name: Change the ownership of the new snowbound war file
      file:
        path: /opt/app/acm/snowbound/webapps/VirtualViewerJavaHTML5.war
        owner: snowbound
        group: snowbound
        mode: 0755
      when: state.stat.isdir is defined and state.stat.isdir
        
    - name: Include Restart Role
      include_role: 
        name: RestartService
      vars:
        service_name: snowbound
      when: state.stat.isdir is defined and state.stat.isdir
      