---
# tasks file for CreateFolder
  - name: Execute create new folder
    uri:
      url: https://{{ ALF_HOST }}:{{ ALF_PORT }}/alfresco/s/api/site/folder/acm/documentlibrary
      method: POST
      user: admin
      password: admin
      body: '{"name": "Recycle Bin", "title": "Recycle Bin"}'
      body_format: json
      status_code: 200, 500
      headers:
        Content-Type: "application/json"