---
# tasks file for CreateFolder
  # - name: Execute CURL 2
    # uri:
      # url: https://{{ ALF_HOST }}:{{ ALF_PORT }}/alfresco/s/api/site/folder/acm/documentlibrary
      # method: POST
      # user: admin
      # password: admin
      # headers:
        # Content-Type: "application/json"
      # src: file.json
    - name: Execute CURL to create new folder
      command: 'curl -k -u admin:admin -H "content-type: application/json" -d "{ \"name\": \"Recycle Bin1\", \"title\": \"Recycle Bin1\"}" -X POST "https://acm-alfresco:8443/alfresco/s/api/site/folder/acm/documentlibrary"'
      
    